/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VisionApiTest;

import Service.ServerSocketForImage;

public class App {

    public static void main(String... args) throws Exception {
        // Initialize client that will be used to send requests. This client only needs to be created
        // once, and can be reused for multiple requests. After completing all of your requests, call
        // the "close" method on the client to safely clean up any remaining background resources.

        new ServerSocketForImage().start();
<<<<<<< HEAD
     
=======

        //ExecutorService singleExecutor = Executors.newSingleThreadExecutor();
        //singleExecutor.execute(new ServiceExecutorApi());
>>>>>>> 0c049a57b984b4b712ce00f26ebd8d34ccd1d65c
    }
}
