/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VisionApiTest;

import Api.ServiceExecutorApi;
import Service.ServerSocketForImage;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;


public class App {

    public static void main(String... args) throws Exception {
        // Initialize client that will be used to send requests. This client only needs to be created
        // once, and can be reused for multiple requests. After completing all of your requests, call
        // the "close" method on the client to safely clean up any remaining background resources.

        new ServerSocketForImage().start();

        //ExecutorService singleExecutor = Executors.newSingleThreadExecutor();
        //singleExecutor.execute(new ServiceExecutorApi());
    }
}
